import './global.css';
//👇 Import our second font
import {
  Inter as Sans,
  Bitter as Serif,
  Fira_Code as Mono,
} from 'next/font/google';

export const metadata = {
  title: 'Welcome to staytus-ui',
  description: 'Generated by create-nx-workspace',
};
const sans = Sans({
  subsets: ['latin'],
  // this will be the css variable
  variable: '--font-sans',
});

const serif = Serif({
  subsets: ['latin'],
  variable: '--font-serif',
});
const mono = Mono({
  subsets: ['latin'],
  variable: '--font-mono',
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${mono.variable} ${sans.variable} ${serif.variable} font-sans overflow-x-hidden`}
    >
      <body>{children}</body>
    </html>
  );
}
